import Head from "next/head";
import { GetStaticProps, GetStaticPaths } from "next";

import { getAllPosts, getPostsForTopPage, getPostsByPage, getNumberOfPages, getPostsByTagAndPage, getNumberOfPagesByTag, getAllTags } from "../../../../../../lib/notionAPI";
import Pagination from "../../../../../../components/Pagination/Pagination";
import SinglePost from "../../../../../../components/Post/SinglePost";
import Tag from "../../../../../../components/Tag/Tag";

export const getStaticPaths: GetStaticPaths = async () => {
  const allTags = await getAllTags();
  let params = [];

  await Promise.all(
    allTags.map((tag: string) => {
      return getNumberOfPagesByTag(tag).then((numberOfPagesByTag: number) => {
        for(let i = 1; i <= numberOfPagesByTag; i++) {
          params.push({params: { tag: tag, page: i.toString() }});
        }
      });
    })
  );

  // console.log(params);

  return {
    paths: params,
    fallback: "blocking"
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const currentPage: string = context.params?.page.toString();
  const currentTag: string = context.params?.tag.toString();

  const upperCaseCurrentTag = currentTag.charAt(0).toUpperCase() + currentTag.slice(1);

  const posts = await getPostsByTagAndPage(
    upperCaseCurrentTag, 
    parseInt(currentPage, 10)
  );

  const numberOfPagesByTag = await getNumberOfPagesByTag(upperCaseCurrentTag);

  const allTags = await getAllTags();

  return {
    props: {
      posts,
      numberOfPagesByTag,
      currentTag,
      allTags,
    },
    revalidate: 60,
  };
};


const BlogTagPageList = ({ numberOfPagesByTag, posts, currentTag, allTags }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">Notion-Blog🚀</h1>
        <section className="md:grid grid-cols-2 lg:w-5/6 lg:mx-auto gap-3 mx-4">
          {posts.map((post) => (
            <div key={post.id}>
              <SinglePost 
                title={post.title}
                description={post.description}
                date={post.date}
                tags={post.tags}
                slug={post.slug}
                isPagenationPage={true}
                />
            </div>
          ))}
        </section>
        <Pagination numberOfPage={numberOfPagesByTag} tag={currentTag} />
        <Tag tags={allTags} />
      </main>
    </div>
  );
};

export default BlogTagPageList;